name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: shopapi.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build -t local-image:latest .
        docker tag local-image:latest shopapi.azurecr.io/shop-app:latest

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push shopapi.azurecr.io/shop-app:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: shop-app
        slot-name: production
        images: shopapi.azurecr.io/shop-app:latest
